version: "3.8"
services:
 catalog-service:
  depends_on:
   - uabook-postgres
  image: "catalog-service"
  container_name: "catalog-service"
  ports:
   - 9001:9001
   - 8001:8001
  environment: 
   - BPL_JVM_THREAD_COUNT=50
   - BPL_DEBUG_ENABLED=true
   - BPL_DEBUG_PORT=8001
   - SPRING_DATASOURCE_URL=jdbc:postgresql://uabook-postgres:5432/uabookdb_catalog
   - SPRING_PROFILES_ACTIVE=testdata

 order-service:
  depends_on:
   - uabook-postgres
  #image: "ghcr.io/volskyi-dmytro/order-service:latest"
  image: "order-service:0.0.1-SNAPSHOT"
  #image: "order-service"
  container_name: "order-service"
  ports:
   - 9002:9002
   - 8002:8002
  environment:
  # Buildpacks environment variable to enable debug through a socket on port 8002
   - BPL_DEBUG_ENABLED=true
   - BPL_DEBUG_PORT=8002
   - UABOOK_CATALOG_SERVICE_URI=http://catalog-service:9001
   - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
   - SPRING_R2DBC_URL=r2dbc:postgresql://uabook-postgres:5432/uabookdb_order
   - SPRING_FLYWAY_URL=jdbc:postgresql://uabook-postgres:5432/uabookdb_order

 uabook-postgres:
  image: "postgres:14.4"
  container_name: "uabook-postgres"
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=user
   - POSTGRES_PASSWORD=password
  volumes:
   - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

 uabook-redis:
  image: "redis:7.0"
  container_name: "uabook-redis"
  ports:
   - 6379:6379
